app/network/views.py
# -*- coding: utf-8 -*-
"""
app.network.views
~~~~~~~~~~~~~~~~~

This module implements the network blueprint.

:copyright: (c) 2017 European Spallation Source ERIC
:license: BSD 2-Clause, see LICENSE for more details.

"""
import ipaddress
import sqlalchemy as sa
from flask import (
    Blueprint,
    render_template,
    jsonify,
    session,
    redirect,
    url_for,
    request,
    flash,
    current_app,
    abort,
)
from flask_login import login_required, current_user
from wtforms import ValidationError
from .forms import (
    HostForm,
    InterfaceForm,
    HostInterfaceForm,
    NetworkForm,
    EditNetworkForm,
    NetworkScopeForm,
    DomainForm,
    CreateVMForm,
    AnsibleGroupForm,
    BootProfileForm,
)
from ..extensions import db
from ..decorators import login_groups_accepted
from .. import models, utils

bp = Blueprint("network", __name__)


@bp.route("/_retrieve_hosts", methods=["POST"])
@login_required
def retrieve_hosts():
    return utils.retrieve_data_for_datatables(
        request.values, models.Host, filter_sensitive=True
    )


@bp.route("/hosts")
@login_required
def list_hosts():
    return render_template("network/hosts.html")


@bp.route("/hosts/create", methods=("GET", "POST"))
@login_groups_accepted("admin", "network")
def create_host():
    kwargs = {"random_mac": True}
    # Try to get the network_id from the session
    # to pre-fill the form with the same network
    if session.get("network_id"):
        kwargs["network_id"] = session["network_id"]
    # Same for the device_type
    if session.get("device_type_id"):
        kwargs["device_type_id"] = session["device_type_id"]
    form = HostInterfaceForm(request.form, **kwargs)
    # Remove the host_id field inherited from the InterfaceForm
    # It's not used in this form
    del form.host_id
    # First interface name shall be identical to host name
    del form.interface_name
    # Interface description can only be added when adding or editing interface
    del form.interface_description
    if form.validate_on_submit():
        device_type_id = form.device_type_id.data
        network_id = form.network_id.data
        network = models.Network.query.get(network_id)
        if not current_user.has_access_to_network(network):
            abort(403)
        ansible_groups = [
            models.AnsibleGroup.query.get(id_) for id_ in form.ansible_groups.data
        ]
        try:
            host = models.Host(
                name=form.name.data,
                device_type=models.DeviceType.query.get(device_type_id),
                is_ioc=form.is_ioc.data,
                description=form.description.data or None,
                ansible_vars=form.ansible_vars.data or None,
                ansible_groups=ansible_groups,
            )
            interface = models.Interface(
                host=host,
                name=form.name.data,
                ip=form.ip.data,
                mac=form.mac.data,
                network=network,
            )
            interface.cnames = [
                models.Cname(name=name) for name in form.cnames_string.data.split()
            ]
        except ValidationError as e:
            # Check for error raised by model validation (not implemented in form validation)
            current_app.logger.warning(f"{e}")
            flash(f"{e}", "error")
            return render_template("network/create_host.html", form=form)
        current_app.logger.debug(f"Trying to create: {host}")
        db.session.add(host)
        try:
            db.session.commit()
        except sa.exc.IntegrityError as e:
            db.session.rollback()
            current_app.logger.warning(f"{e}")
            flash(f"{e}", "error")
        else:
            current_app.logger.info(
                f"Host {host} created by {current_user}: {host.to_dict()}"
            )
            flash(f"Host {host} created!", "success")
        # Save network_id and device_type_id to the session to retrieve them after the redirect
        session["network_id"] = network_id
        session["device_type_id"] = device_type_id
        return redirect(url_for("network.view_host", name=host.name))
    return render_template("network/create_host.html", form=form)


@bp.route("/hosts/delete", methods=["POST"])
@login_required
def delete_host():
    host = models.Host.query.get_or_404(request.form["host_id"])
    if not current_user.can_delete_host(host):
        abort(403)
    # Deleting the host will also delete all
    # associated interfaces due to the cascade delete option
    # defined on the model
    db.session.delete(host)
    db.session.commit()
    current_app.logger.info(f"Host {host} deleted by {current_user}")
    flash(f"Host {host.name} has been deleted", "success")
    if host.device_type.name == "VirtualMachine":
        flash(
            "Note that the host was only removed from CSEntry. "
            "To delete a running VM, please contact an administrator.",
            "info",
        )
    return redirect(url_for("network.list_hosts"))


@bp.route("/hosts/view/<name>", methods=("GET", "POST"))
@login_required
def view_host(name):
    host = models.Host.query.filter_by(name=name).first_or_404()
    if not current_user.can_view_host(host):
        abort(403)
    if host.main_interface is None:
        flash(f"Host {host.name} has no interface! Add one or delete it.", "warning")
    elif host.main_interface.name != host.name:
        flash(
            f"The main interface '{host.main_interface.name}' shall have the same name as the host!"
            f" Please rename it '{host.name}'.",
            "warning",
        )
    if (
        host.device_type.name
        in current_app.config["ALLOWED_SET_BOOT_PROFILE_DEVICE_TYPES"]
    ):
        form = BootProfileForm()
    elif host.device_type.name.startswith("Virtual"):
        form = CreateVMForm()
        if host.is_ioc:
            for field in ("cores", "memory", "disk", "osversion"):
                key = f"VIOC_{field.upper()}_CHOICES"
                getattr(form, field).choices = utils.get_choices(
                    current_app.config[key]
                )
    else:
        form = None
    if form is not None and form.validate_on_submit():
        if (
            host.device_type.name
            in current_app.config["ALLOWED_SET_BOOT_PROFILE_DEVICE_TYPES"]
        ):
            if not current_user.can_set_boot_profile(host):
                flash(
                    "You don't have the proper permissions to set the boot profile. Please contact an admin user.",
                    "warning",
                )
                return redirect(url_for("network.view_host", name=name))
            else:
                boot_profile = form.boot_profile.data
                task = utils.trigger_set_network_boot_profile(
                    host, boot_profile=boot_profile
                )
                # For localboot, there is no need to update the variable
                # csentry_autoinstall_boot_profile is used for DHCP options
                if boot_profile != "localboot" and utils.update_ansible_vars(
                    host, {"csentry_autoinstall_boot_profile": boot_profile}
                ):
                    # If a change occured, force DHCP update
                    utils.trigger_core_services_update()
                db.session.commit()
                current_app.logger.info(
                    f"Set network boot profile to {boot_profile} for {name} requested by {current_user}: task {task.id}"
                )
                flash(
                    f"Set network boot profile to {boot_profile} for {name} requested! "
                    "Refresh the page to update the status. You can reboot the machine when the task is done.",
                    "success",
                )
                return redirect(url_for("task.view_task", id_=task.id))
        else:
            if not current_user.can_create_vm(host):
                flash(
                    "You don't have the proper permissions to create this VM. Please contact an admin user.",
                    "warning",
                )
                return redirect(url_for("network.view_host", name=name))
            else:
                task = utils.trigger_vm_creation(
                    host,
                    vm_disk_size=int(form.disk.data),
                    vm_cores=int(form.cores.data),
                    vm_memory=int(form.memory.data) * 1024,
                    vm_osversion=form.osversion.data,
                    skip_post_install_job=form.skip_post_install_job.data,
                )
                db.session.commit()
                current_app.logger.info(
                    f"Creation of {name} requested by {current_user}: task {task.id}"
                )
                flash(
                    f"Creation of {name} requested! Refresh the page to update the status.",
                    "success",
                )
                return redirect(url_for("task.view_task", id_=task.id))
    return render_template("network/view_host.html", host=host, form=form)


@bp.route("/hosts/edit/<name>", methods=("GET", "POST"))
@login_groups_accepted("admin", "network")
def edit_host(name):
    host = models.Host.query.filter_by(name=name).first_or_404()
    if not current_user.has_access_to_network(host.main_network):
        abort(403)
    form = HostForm(request.form, obj=host)
    # Passing ansible_groups as kwarg to the HostForm doesn't work because
    # obj takes precedence (but host.ansible_groups contain AnsibleGroup instances and not id)
    # We need to update the default values. Calling process is required.
    # See https://stackoverflow.com/questions/5519729/wtforms-how-to-select-options-in-selectmultiplefield
    form.ansible_groups.default = [group.id for group in host.ansible_groups]
    form.ansible_groups.process(request.form)
    if form.validate_on_submit():
        try:
            host.name = form.name.data

app/templates/network/create_group.html
{% extends "network/groups.html" %}
{% from "_helpers.html" import render_field %}

{% block title %}Register Ansible group{% endblock %}

{% block groups_main %}
  <form id="groupForm" method="POST">
    {{ form.hidden_tag() }}
    {{ render_field(form.name, class_="text-lowercase") }}
    {{ render_field(form.vars) }}
    {{ render_field(form.type) }}
    {{ render_field(form.children, class_="selectize-default") }}
    {{ render_field(form.hosts, class_="selectize-default") }}
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
{%- endblock %}

app/templates/network/create_host.html
{% extends "network/hosts.html" %}
{% from "_helpers.html" import render_field %}

{% block title %}Register Host{% endblock %}

{% block hosts_main %}
  <form id="hostForm" method="POST">
    {{ form.hidden_tag() }}
    {{ render_field(form.name, class_="text-lowercase") }}
    {{ render_field(form.device_type_id, class_="selectize-default") }}
    {{ render_field(form.is_ioc) }}
    {{ render_field(form.description) }}
    {{ render_field(form.network_id, class_="selectize-default") }}
    {{ render_field(form.ip) }}
    {{ render_field(form.random_mac) }}
    {{ render_field(form.mac) }}
    {{ render_field(form.cnames_string) }}
    {{ render_field(form.ansible_vars) }}
    {{ render_field(form.ansible_groups, class_="selectize-default") }}
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
{%- endblock %}

app/templates/network/create_network.html
{% extends "network/networks.html" %}
{% from "_helpers.html" import render_field %}

{% block title %}Register Network{% endblock %}

{% block networks_main %}
  <form id="networkForm" method="POST">
    {{ form.hidden_tag() }}
    {{ render_field(form.scope_id) }}
    {{ render_field(form.vlan_name) }}
    {{ render_field(form.vlan_id) }}
    {{ render_field(form.description) }}
    {{ render_field(form.prefix) }}
    {{ render_field(form.address) }}
    {{ render_field(form.first_ip) }}
    {{ render_field(form.last_ip) }}
    {{ render_field(form.gateway) }}
    {{ render_field(form.domain_id) }}
    {{ render_field(form.admin_only) }}
    {{ render_field(form.sensitive) }}
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
{%- endblock %}

app/templates/network/create_scope.html
{% extends "network/scopes.html" %}
{% from "_helpers.html" import render_field %}

{% block title %}Register Network Scope{% endblock %}

{% block scopes_main %}
  <form id="scopeForm" method="POST">
    {{ form.hidden_tag() }}
    {{ render_field(form.name) }}
    {{ render_field(form.description) }}
    {{ render_field(form.first_vlan) }}
    {{ render_field(form.last_vlan) }}
    {{ render_field(form.supernet) }}
    {{ render_field(form.domain_id) }}
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
{%- endblock %}

app/templates/network/domains.html
{% extends "base-fluid.html" %}
{% from "_helpers.html" import is_active %}

{% block title %}Domains{% endblock %}

{% block main %}
  {% set path = request.path %}
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link {{ is_active(path.endswith("/network/domains")) }}" href="{{ url_for('network.list_domains') }}">List domains</a>
    </li>
    <li class="nav-item">
      <a class="nav-link {{ is_active(path.startswith("/network/domains/create")) }}" href="{{ url_for('network.create_domain') }}">Register new domain</a>
    </li>
    {% block domains_nav %}{% endblock %}
  </ul>

  <br>

  {% block domains_main %}
  <table id="domains_table" class="table table-bordered table-hover table-sm" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      {% for domain in domains %}
        <tr>
          <td>{{ domain.name }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {%- endblock %}
{%- endblock %}

{% block csentry_scripts %}
  <script src="{{ url_for('static', filename='js/domains.js') }}"></script>
{% endblock %}

app/templates/network/edit_group.html
{% extends "network/groups.html" %}
{% from "_helpers.html" import render_field %}

{% block title %}Edit {{ form.name.data }} Ansible group{% endblock %}

{% block groups_nav %}
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('network.view_ansible_group', name=form.name.data) }}">View group</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ url_for('network.edit_ansible_group', name=form.name.data) }}">Edit group</a>
    </li>
{% endblock %}

{% block groups_main %}
  <form id="editGroupForm" method="POST">
    {{ form.hidden_tag() }}
    {{ render_field(form.name, class_="text-lowercase") }}
    {{ render_field(form.vars) }}
    {{ render_field(form.type) }}
    {{ render_field(form.children, class_="selectize-default") }}
    {{ render_field(form.hosts, class_="selectize-default") }}
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
{%- endblock %}

app/templates/network/edit_host.html
{% extends "network/hosts.html" %}
{% from "_helpers.html" import render_field %}

{% block title %}Edit {{ form.name.data }} host{% endblock %}

{% block hosts_nav %}
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('network.view_host', name=form.name.data) }}">View host</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ url_for('network.edit_host', name=form.name.data) }}">Edit host</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('network.create_interface', hostname=form.name.data) }}">Add interface</a>
    </li>
{% endblock %}

{% block hosts_main %}
  <form id="editHostForm" method="POST">
    {{ form.hidden_tag() }}
    {{ render_field(form.name, class_="text-lowercase") }}
    {{ render_field(form.device_type_id, class_="selectize-default") }}
    {{ render_field(form.is_ioc) }}
    {{ render_field(form.description) }}
    {{ render_field(form.ansible_vars) }}
    {{ render_field(form.ansible_groups, class_="selectize-default") }}
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
{%- endblock %}

app/templates/network/edit_network.html
{% extends "network/networks.html" %}
{% from "_helpers.html" import render_field %}

{% block title %}Edit {{ form.vlan_name.data }} network{% endblock %}

{% block networks_nav %}
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('network.view_network', vlan_name=form.vlan_name.data) }}">View network</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ url_for('network.edit_network', vlan_name=form.vlan_name.data) }}">Edit network</a>
    </li>
{% endblock %}

{% block networks_main %}
  <form id="editNetworkForm" method="POST">
    {{ form.hidden_tag() }}
    {{ render_field(form.vlan_name) }}
    {{ render_field(form.vlan_id) }}
    {{ render_field(form.description) }}
    {{ render_field(form.address) }}
    {{ render_field(form.first_ip) }}
    {{ render_field(form.last_ip) }}
    {{ render_field(form.gateway) }}
    {{ render_field(form.domain_id) }}
    {{ render_field(form.admin_only) }}
    {{ render_field(form.sensitive) }}
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
{%- endblock %}

app/templates/network/hosts.html
{% extends "base-fluid.html" %}
{% from "_helpers.html" import is_active %}

{% block title %}Hosts{% endblock %}

{% block main %}
  {% set path = request.path %}
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link {{ is_active(path.endswith("/network/hosts")) }}" href="{{ url_for('network.list_hosts') }}">List hosts</a>
    </li>
    <li class="nav-item">
      <a class="nav-link {{ is_active(path.startswith("/network/hosts/create")) }}" href="{{ url_for('network.create_host') }}">Register new host</a>
    </li>
    {% block hosts_nav %}{% endblock %}
  </ul>

  <br>

  {% block hosts_main %}
  <table id="hosts_table" class="table table-bordered table-hover table-sm" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Hostname</th>
        <th>Type</th>
        <th>Description</th>
        <th>IP</th>
        <th>MAC</th>
        <th>Network</th>
      </tr>
    </thead>
  </table>
  {%- endblock %}
{%- endblock %}

{% block csentry_scripts %}
  <script src="{{ url_for('static', filename='js/hosts.js') }}"></script>
{% endblock %}

app/templates/network/networks.html
{% extends "base-fluid.html" %}
{% from "_helpers.html" import is_active, link_to_network, link_to_scope %}

{% block title %}Networks{% endblock %}

{% block main %}
{% set path = request.path %}
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link {{ is_active(path.endswith("/network/networks")) }}"
      href="{{ url_for('network.list_networks') }}">List networks</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {{ is_active(path.startswith("/network/networks/create")) }}"
      href="{{ url_for('network.create_network') }}">Register new network</a>
  </li>
  {% block networks_nav %}{% endblock %}
</ul>

<br>

{% block networks_main %}
<table id="networks_table" class="table table-bordered table-hover table-sm" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Vlan name</th>
      <th>Vlan id</th>
      <th>Description</th>
      <th>Address</th>
      <th>First IP</th>
      <th>Last IP</th>
      <th>Gateway</th>
      <th>Network scope</th>
      <th>Domain</th>
      <th>Admin only</th>
      <th>Sensitive</th>
    </tr>
  </thead>
  <tbody>
    {% for network in networks %}
    <tr>
      <td>{{ link_to_network(network) }}</td>
      <td>{{ network.vlan_id }}</td>
      <td>{{ network.description | safe }}</td>
      <td>{{ network.address }}</td>
      <td>{{ network.first_ip }}</td>
      <td>{{ network.last_ip }}</td>
      <td>{{ network.gateway }}</td>
      <td>{{ link_to_scope(network.scope) }}</td>
      <td>{{ network.domain }}</td>
      <td>{{ network.admin_only }}</td>
      <td>{{ network.sensitive }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{%- endblock %}
{%- endblock %}

{% block csentry_scripts %}
<script src="{{ url_for('static', filename='js/networks.js') }}"></script>
{% endblock %}

app/templates/network/view_host.html
{% extends "network/hosts.html" %}
{% from "_helpers.html" import link_to_items, link_to_stack_members,
   link_to_ansible_groups, link_to_network,
   delete_button_with_confirmation, render_field, submit_button_with_confirmation %}

{% block title %}View {{ host.name }} host{% endblock %}

{% block hosts_nav %}
    <li class="nav-item">
      <a class="nav-link active" href="{{ url_for('network.view_host', name=host.name) }}">View host</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('network.edit_host', name=host.name) }}">Edit host</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('network.create_interface', hostname=host.name) }}">Add interface</a>
    </li>
{% endblock %}

{% block hosts_main %}
  <div class="row">
    <div class="col-sm-8">
      <dl class="row">
        <dt class="col-sm-3">Hostname</dt>
        <dd class="col-sm-9">
          <div class="row">
            <div class="col-sm-10">
              {{ host.fqdn }}
            </div>
            <div class="col-sm-2 text-right">
              <form method="POST" action="/network/hosts/delete">
                <input id="host_id" name="host_id" type="hidden" value="{{ host.id }}">
                {{ delete_button_with_confirmation("Delete host", "deleteConfirmation-%s" | format(host.id),
                   "Are you sure you want to delete the host %s?" | format(host.name)) }}
              </form>
            </div>
          </div>
        </dd>
        <dt class="col-sm-3">Device Type</dt>
        <dd class="col-sm-9">{{ host.device_type }}</dd>
        <dt class="col-sm-3">IOC</dt>
        <dd class="col-sm-9">{{ host.is_ioc }}</dd>
        {% if host.items %}
        <dt class="col-sm-3">Items</dt>
        <dd class="col-sm-9">{{ link_to_items(host.items) }}</dd>
        {% endif %}
        {% if host.stack_members() %}
        <dt class="col-sm-3">Stack Members</dt>
        <dd class="col-sm-9">{{ link_to_stack_members(host.stack_members()) }}</dd>
        {% endif %}
        <dt class="col-sm-3">Description</dt>
        <dd class="col-sm-9">{{ host.description }}</dd>
        <dt class="col-sm-3">Created by</dt>
        <dd class="col-sm-9">{{ host.user }}</dd>
        <dt class="col-sm-3">Created at</dt>
        <dd class="col-sm-9">{{ host.created_at | datetimeformat }}</dd>
        {% if host.ansible_vars %}
        <dt class="col-sm-3">Ansible vars</dt>
        <dd class="col-sm-9"><pre>{{ host.ansible_vars | toyaml }}</pre></dd>
        {% endif %}
        {% if host.ansible_groups %}
        <dt class="col-sm-3">Ansible groups</dt>
        <dd class="col-sm-9">{{ link_to_ansible_groups(host.ansible_groups) }}</dd>
        {% endif %}
      </dl>
    </div>
    {% if host.device_type.name.startswith('Virtual') %}
      {% if host.is_ioc %}
        {% set vm_type = 'Virtual IOC' %}
      {% else %}
        {% set vm_type = 'VM' %}
      {% endif %}
      <div class="col-sm-4">
        <form id="createVMForm" method="POST">
          {{ form.hidden_tag() }}
          {{ render_field(form.cores, label_size='5', input_size='7') }}
          {{ render_field(form.memory, label_size='5', input_size='7') }}
          {{ render_field(form.disk, label_size='5', input_size='7') }}
          {{ render_field(form.osversion, label_size='5', input_size='7') }}
          {% if current_user.is_admin %}
          {{ render_field(form.skip_post_install_job, label_size='5', input_size='7') }}
          {% endif %}
          {{ submit_button_with_confirmation('Create ' + vm_type, 'Do you really want to create the ' + vm_type + ' ' + host.name + '?', 'Note: If you are experiencing issues with the VM, pressing "Create VM" once more will not resolve anything and you should instead contact the INFRA team or create a JIRA ticket to resolve this.') }}
        </form>
      </div>
    {% elif host.device_type.name in config.ALLOWED_SET_BOOT_PROFILE_DEVICE_TYPES %}
      <div class="col-sm-4">
        <form id="BootProfileForm" method="POST">
          {{ form.hidden_tag() }}
          {{ render_field(form.boot_profile, label_size='5', input_size='7') }}
          {{ submit_button_with_confirmation('Set boot profile', 'Do you really want to set the boot profile for ' + host.name + '?') }}
        </form>
      </div>
    {% endif %}
  </div>
  <h3>Interfaces</h3>
  <table id="interfaces_table" class="table table-hover table-sm">
    <thead>
      <tr>
        <th width="5%"></th>
        <th>Name</th>
        <th>Description</th>
        <th>Cnames</th>
        <th>IP</th>
        <th>MAC</th>
        <th>Network</th>
      </tr>
    </thead>
    <tbody>
      {% for interface in host.interfaces %}
      <tr>
        <td class="btn-group mr-2" role="group" aria-label="edit delete interface">
          <a class="btn btn-light" role="button" href="{{ url_for('network.edit_interface', name=interface.name) }}" title="Edit interface">
              <span class="oi oi-pencil" aria-hidden="true"></span>
          </a>
          <form method="POST" action="/network/interfaces/delete">
            <input id="interface_id" name="interface_id" type="hidden" value="{{ interface.id }}">
            {{ delete_button_with_confirmation("Delete interface", "deleteConfirmation-%s" | format(interface.id),
               "Are you sure you want to delete interface %s?" | format(interface.name)) }}
          </form>
        </td>
        <td>{{ interface.name }}</td>
        <td>{{ interface.description if interface.description }}</td>
        <td>{{ interface.cnames | join(' ') }}</td>
        <td>{{ interface.ip }}</td>
        <td>{{ interface.mac }}</td>
        <td>{{ link_to_network(interface.network) }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <h3>History</h3>
  <table id="host_version_table" class="table table-hover table-sm">
    <thead>
      <tr>
        <th>Updated at</th>
        <th>Updated by</th>
        <th>Name</th>
        <th>Device Type</th>
        <th>Ansible variables</th>
        <th>Ansible groups</th>
      </tr>
    </thead>
    <tbody>
      {% for version in host.versions | reverse %}
      <tr>
        <td>{{ version.transaction.issued_at | datetimeformat }}</td>
        <td>{{ version.transaction.user }}</td>
        <td>{{ version.name }}</td>
        <td>{{ version.device_type }}</td>
        <td><pre>{{ version.ansible_vars | toyaml }}</pre></td>
        <td>{{ link_to_ansible_groups(version.ansible_groups) }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{%- endblock %}