app/task/views.py
# -*- coding: utf-8 -*-
"""
app.task.views
~~~~~~~~~~~~~~

This module implements the task blueprint.

:copyright: (c) 2018 European Spallation Source ERIC
:license: BSD 2-Clause, see LICENSE for more details.

"""
from flask import Blueprint, render_template, jsonify, request
from flask_login import login_required, current_user
from .. import models

bp = Blueprint("task", __name__)


@bp.route("/tasks")
@login_required
def list_tasks():
    return render_template("task/tasks.html")


@bp.route("/tasks/view/<id_>")
@login_required
def view_task(id_):
    task = models.Task.query.get_or_404(id_)
    return render_template("task/view_task.html", task=task)


@bp.route("/_retrieve_tasks")
@login_required
def retrieve_tasks():
    all = request.args.get("all", "false") == "true"
    data = [task.to_dict() for task in current_user.get_tasks(all=all)]
    return jsonify(data=data)

app/templates/task/tasks.html
{% extends "base-fluid.html" %}
{% from "_helpers.html" import is_active %}

{% block title %}Tasks{% endblock %}

{% block main %}
  {% set path = request.path %}
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link {{ is_active(path.endswith("/task/tasks")) }}" href="{{ url_for('task.list_tasks') }}">List tasks</a>
    </li>
    {% block tasks_nav %}{% endblock %}
  </ul>

  <br>

  {% block tasks_main %}
  {% if current_user.is_authenticated and current_user.is_admin %}
    <div class="form-check">
      <input class="form-check-input" type="checkbox" value="" id="allTasks">
      <label class="form-check-label" for="allTasks">
        Show all tasks (all users)
      </label>
    </div>

    <hr class="separator">
  {%- endif %}

  <table id="tasks_table" class="table table-bordered table-hover table-sm" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Created at</th>
        <th>Ended at</th>
        <th>Status</th>
        <th>AWX job</th>
        <th>Depends on</th>
        <th>Command</th>
        <th>User</th>
      </tr>
    </thead>
  </table>
  {%- endblock %}
{%- endblock %}

{% block csentry_scripts %}
  <script src="{{ url_for('static', filename='js/tasks.js') }}"></script>
{% endblock %}

app/templates/task/view_task.html
{% extends "task/tasks.html" %}
{% from "_helpers.html" import link_to_task, link_to_tasks %}

{% block title %}View {{ task.name }} task{% endblock %}

{% block tasks_nav %}
    <li class="nav-item">
      <a class="nav-link active" href="{{ url_for('task.view_task', id_=task.id) }}">View task</a>
    </li>
{% endblock %}

{% block tasks_main %}
  <div class="row">
    <div class="col-sm-9">
      <dl class="row">
        <dt class="col-sm-3">Id</dt>
        <dd class="col-sm-9">{{ task.id }}</dd>
        <dt class="col-sm-3">Name</dt>
        <dd class="col-sm-9">{{ task.name }}</dd>
        <dt class="col-sm-3">Created at</dt>
        <dd class="col-sm-9">{{ task.created_at }}</dd>
        <dt class="col-sm-3">Ended at</dt>
        <dd class="col-sm-9">{{ task.ended_at }}</dd>
        <dt class="col-sm-3">Status</dt>
        <dd class="col-sm-9">{{ task.status.name }}</dd>
        <dt class="col-sm-3">AWX resource</dt>
        <dd class="col-sm-9">{{ task.awx_resource }}</dd>
        <dt class="col-sm-3">AWX job</dt>
        {% if task.awx_job_id %}
        <dd class="col-sm-9"><a href="{{ task.awx_job_url }}">{{ task.awx_job_id }}</a></dd>
        {% else %}
        <dd class="col-sm-9">{{ task.awx_job_id }}</dd>
        {% endif %}
        <dt class="col-sm-3">Depends on</dt>
        <dd class="col-sm-9">{{ link_to_task(task.depends_on) }}</dd>
        <dt class="col-sm-3">Reverse dependencies</dt>
        <dd class="col-sm-9">{{ link_to_tasks(task.reverse_dependencies) }}</dd>
        {% if task.exception %}
        <dt class="col-sm-3">Exception</dt>
        <dd class="col-sm-9"><pre>{{ task.exception }}</pre></dd>
        {% endif %}
        <dt class="col-sm-3">Command</dt>
        <dd class="col-sm-9">{{ task.command }}</dd>
        <dt class="col-sm-3">User</dt>
        <dd class="col-sm-9">{{ task.user }}</dd>
      </dl>
    </div>
  </div>
{%- endblock %}