app/inventory/forms.py
# -*- coding: utf-8 -*-
"""
app.inventory.forms
~~~~~~~~~~~~~~~~~~~

This module defines the inventory blueprint forms.

:copyright: (c) 2017 European Spallation Source ERIC
:license: BSD 2-Clause, see LICENSE for more details.

"""
from wtforms import SelectField, StringField, IntegerField, TextAreaField, validators
from ..helpers import CSEntryForm
from ..validators import (
    Unique,
    RegexpList,
    ICS_ID_RE,
    MAC_ADDRESS_RE,
    NoValidateSelectField,
)
from .. import utils, models


class AttributeForm(CSEntryForm):
    name = StringField("Name", validators=[validators.DataRequired()])
    description = StringField("Description")


class ItemForm(CSEntryForm):
    ics_id = StringField(
        "ICS id",
        validators=[
            validators.InputRequired(),
            validators.Regexp(
                ICS_ID_RE,
                message="The ICS id shall be composed of 3 letters and 3 digits.",
            ),
            Unique(models.Item, "ics_id"),
        ],
    )
    serial_number = StringField(
        "Serial number", validators=[validators.InputRequired()]
    )
    quantity = IntegerField(
        "Quantity", default=1, validators=[validators.NumberRange(min=1)]
    )
    manufacturer_id = SelectField("Manufacturer", coerce=utils.coerce_to_str_or_none)
    model_id = SelectField("Model", coerce=utils.coerce_to_str_or_none)
    location_id = SelectField("Location", coerce=utils.coerce_to_str_or_none)
    status_id = SelectField("Status", coerce=utils.coerce_to_str_or_none)
    parent_id = SelectField("Parent", coerce=utils.coerce_to_str_or_none)
    host_id = SelectField("Host", coerce=utils.coerce_to_str_or_none)
    stack_member = NoValidateSelectField(
        "Stack member", coerce=utils.coerce_to_int_or_none, choices=[]
    )
    mac_addresses = StringField(
        "MAC addresses",
        description="space separated list of MAC addresses",
        validators=[
            validators.Optional(),
            RegexpList(MAC_ADDRESS_RE, message="Invalid MAC address"),
        ],
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.manufacturer_id.choices = utils.get_model_choices(
            models.Manufacturer, allow_none=True
        )
        self.model_id.choices = utils.get_model_choices(models.Model, allow_none=True)
        self.location_id.choices = utils.get_model_choices(
            models.Location, allow_none=True
        )
        self.status_id.choices = utils.get_model_choices(models.Status, allow_none=True)
        self.parent_id.choices = utils.get_model_choices(
            models.Item, allow_none=True, attr="ics_id"
        )
        self.host_id.choices = utils.get_model_choices(models.Host, allow_none=True)


class CommentForm(CSEntryForm):
    body = TextAreaField("Enter your comment:", validators=[validators.DataRequired()])


class EditCommentForm(CSEntryForm):
    body = TextAreaField("Edit comment:", validators=[validators.DataRequired()])

app/inventory/views.py
# -*- coding: utf-8 -*-
"""
app.inventory.views
~~~~~~~~~~~~~~~~~~~

This module implements the inventory blueprint.

:copyright: (c) 2017 European Spallation Source ERIC
:license: BSD 2-Clause, see LICENSE for more details.

"""
import sqlalchemy as sa
from flask import (
    Blueprint,
    render_template,
    jsonify,
    session,
    request,
    redirect,
    url_for,
    flash,
    current_app,
)
from flask_login import login_required, current_user
from .forms import AttributeForm, ItemForm, CommentForm, EditCommentForm
from ..extensions import db
from ..decorators import login_groups_accepted
from .. import utils, models, helpers

bp = Blueprint("inventory", __name__)


@bp.route("/_retrieve_items", methods=["POST"])
@login_required
def retrieve_items():
    return utils.retrieve_data_for_datatables(request.values, models.Item)


@bp.route("/items")
@login_required
def list_items():
    return render_template("inventory/items.html")


@bp.route("/items/_generate_excel_file")
@login_required
def _generate_excel_file():
    task = current_user.launch_task(
        "generate_items_excel_file", func="generate_items_excel_file", job_timeout=180
    )
    db.session.commit()
    return utils.redirect_to_job_status(task.id)


@bp.route("/items/create", methods=("GET", "POST"))
@login_groups_accepted("admin", "inventory")
def create_item():
    # The following keys are stored in the session to easily create
    # several identical items
    keys = ("manufacturer_id", "model_id", "location_id", "status_id", "parent_id")
    settings = {key: session.get(key, "") for key in keys}
    form = ItemForm(request.form, **settings)
    if form.validate_on_submit():
        for key in keys:
            session[key] = getattr(form, key).data
        item = models.Item(
            ics_id=form.ics_id.data,
            serial_number=form.serial_number.data,
            quantity=form.quantity.data,
            manufacturer=helpers.get_model(
                models.Manufacturer, form.manufacturer_id.data
            ),
            model=helpers.get_model(models.Model, form.model_id.data),
            location=helpers.get_model(models.Location, form.location_id.data),
            status=helpers.get_model(models.Status, form.status_id.data),
            parent=helpers.get_model(models.Item, form.parent_id.data),
            host=helpers.get_model(models.Host, form.host_id.data),
            stack_member=form.stack_member.data,
        )
        item.macs = [
            models.Mac(address=address) for address in form.mac_addresses.data.split()
        ]
        current_app.logger.debug(f"Trying to create: {item!r}")
        db.session.add(item)
        try:
            db.session.commit()
        except sa.exc.IntegrityError as e:
            db.session.rollback()
            current_app.logger.warning(f"{e}")
            flash(f"{e}", "error")
        else:
            flash(f"Item {item} created!", "success")
        return redirect(url_for("inventory.create_item"))
    return render_template("inventory/create_item.html", form=form)


@bp.route("/items/view/<ics_id>")
@login_required
def view_item(ics_id):
    item = models.Item.query.filter_by(ics_id=ics_id).first_or_404()
    return render_template("inventory/view_item.html", item=item)


@bp.route("/items/comment/<ics_id>", methods=("GET", "POST"))
@login_groups_accepted("admin", "inventory")
def comment_item(ics_id):
    item = models.Item.query.filter_by(ics_id=ics_id).first_or_404()
    form = CommentForm()
    if form.validate_on_submit():
        comment = models.ItemComment(body=form.body.data)
        item.comments.append(comment)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for("inventory.view_item", ics_id=ics_id))
    return render_template("inventory/comment_item.html", item=item, form=form)


@bp.route("/items/comment/edit/<comment_id>", methods=("GET", "POST"))
@login_groups_accepted("admin", "inventory")
def edit_comment(comment_id):
    comment = models.ItemComment.query.get_or_404(comment_id)
    form = EditCommentForm(request.form, obj=comment)
    if form.validate_on_submit():
        comment.body = form.body.data
        # Mark the item as "dirty" to add it to the session so that it will
        # be re-indexed
        sa.orm.attributes.flag_modified(comment.item, "comments")
        db.session.commit()
        return redirect(url_for("inventory.view_item", ics_id=comment.item.ics_id))
    return render_template(
        "inventory/edit_comment.html",
        item=comment.item,
        comment_id=comment.id,
        form=form,
    )


@bp.route("/items/comment/delete", methods=["POST"])
@login_groups_accepted("admin", "inventory")
def delete_comment():
    comment = models.ItemComment.query.get_or_404(request.form["comment_id"])
    ics_id = comment.item.ics_id
    # Explicitely remove the comment from the item to make sure
    # it will be re-indexed
    comment.item.comments.remove(comment)
    db.session.delete(comment)
    db.session.commit()
    flash(f"Comment {comment.id} has been deleted", "success")
    return redirect(url_for("inventory.view_item", ics_id=ics_id))


@bp.route("/items/edit/<ics_id>", methods=("GET", "POST"))
@login_groups_accepted("admin", "inventory")
def edit_item(ics_id):
    item = models.Item.query.filter_by(ics_id=ics_id).first_or_404()
    mac_addresses = " ".join([str(mac) for mac in item.macs])
    form = ItemForm(request.form, obj=item, mac_addresses=mac_addresses)
    if form.validate_on_submit():
        # Only allow to update temporary ics_id
        if item.ics_id.startswith(current_app.config["TEMPORARY_ICS_ID"]):
            item.ics_id = form.ics_id.data
        item.serial_number = form.serial_number.data
        item.quantity = form.quantity.data
        # When a field is disabled, it's value is not passed to the request
        # We don't use request.form.get('stack_member', None) to let the coerce
        # function of the field properly convert the value
        if "stack_member" in request.form:
            item.stack_member = form.stack_member.data
        else:
            # Field is disabled, force it to None
            item.stack_member = None
        item.manufacturer = helpers.get_model(
            models.Manufacturer, form.manufacturer_id.data
        )
        item.model = helpers.get_model(models.Model, form.model_id.data)
        item.location = helpers.get_model(models.Location, form.location_id.data)
        item.status = helpers.get_model(models.Status, form.status_id.data)
        item.parent = helpers.get_model(models.Item, form.parent_id.data)
        item.host = helpers.get_model(models.Host, form.host_id.data)
        new_addresses = form.mac_addresses.data.split()
        # Delete the MAC addresses that have been removed
        for (index, mac) in enumerate(item.macs):
            if mac.address not in new_addresses:
                item.macs.pop(index)
                db.session.delete(mac)
        # Add new MAC addresseses
        for address in new_addresses:
            if address not in mac_addresses:
                mac = models.Mac(address=address)
                item.macs.append(mac)
        current_app.logger.debug(f"Trying to update: {item!r}")
        try:
            db.session.commit()
        except sa.exc.IntegrityError as e:
            db.session.rollback()
            current_app.logger.warning(f"{e}")
            flash(f"{e}", "error")
        else:
            flash(f"Item {item} updated!", "success")
        return redirect(url_for("inventory.view_item", ics_id=item.ics_id))
    return render_template("inventory/edit_item.html", form=form)


@bp.route("/attributes/favorites")
@login_required
def attributes_favorites():
    return render_template("inventory/attributes_favorites.html")


@bp.route("/_retrieve_attributes_favorites")
@login_required
def retrieve_attributes_favorites():
    data = [
        (
            favorite.base64_image(),
            type(favorite).__name__,
            favorite.name,
            favorite.description,
        )
        for favorite in current_user.favorite_attributes()
    ]
    return jsonify(data=data)


@bp.route("/attributes/<kind>", methods=("GET", "POST"))
@login_groups_accepted("admin", "inventory")
def attributes(kind):
    form = AttributeForm()
    if form.validate_on_submit():
        model = getattr(models, kind)
        new_model = model(
            name=form.name.data, description=form.description.data or None
        )
        db.session.add(new_model)
        try:
            db.session.commit()
        except sa.exc.IntegrityError:
            db.session.rollback()
            flash(f"{form.name.data} already exists! {kind} not created.", "error")
        else:
            flash(f"{kind} {new_model} created!", "success")
        return redirect(url_for("inventory.attributes", kind=kind))
    return render_template("inventory/attributes.html", kind=kind, form=form)


@bp.route("/_retrieve_attributes/<kind>")
@login_required
def retrieve_attributes(kind):
    try:
        model = getattr(models, kind)
    except AttributeError:
        raise utils.CSEntryError(f"Unknown model '{kind}'", status_code=422)
    items = db.session.query(model).order_by(model.name)
    data = [
        (
            {"id": item.id, "favorite": item.is_user_favorite()},
            item.base64_image(),
            item.name,
            item.description,
        )
        for item in items
    ]
    return jsonify(data=data)


@bp.route("/_update_favorites/<kind>", methods=["POST"])
@login_required
def update_favorites(kind):
    """Update the current user favorite attributes

    Add or remove the attribute from the favorites when the
    checkbox is checked/unchecked in the attributes table
    """
    try:
        model = getattr(models, kind)
    except AttributeError:
        raise utils.CSEntryError(f"Unknown model '{kind}'", status_code=422)
    data = request.get_json()

app/templates/inventory/attributes.html
{% extends "base-fluid.html" %}
{% from "_helpers.html" import render_field %}

{% block title %}Attributes{% endblock %}

{% block main %}
  <ul class="nav nav-tabs">
    {% for attribute in ('Manufacturer', 'Model', 'Location', 'Status', 'Action') %}
    <li class="nav-item">
      <a class="nav-link {% if attribute == kind %}active{% endif %}" href="{{ url_for('inventory.attributes', kind=attribute) }}">{{ attribute }}</a>
    </li>
    {% endfor %}
    <li class="nav-item">
      <a class="nav-link {{ is_active(request.path.startswith("/inventory/attributes/favorites")) }}" href="{{ url_for('inventory.attributes_favorites') }}">Favorites</a>
    </li>
  </ul>

  <br>

  {% block attributes_main %}
  {% if kind in ('Manufacturer', 'Model', 'Location') or (current_user.is_authenticated and current_user.is_admin and kind != 'Action') %}
    <form id="attributeForm" method="POST">
      {{ form.hidden_tag() }}
      {{ render_field(form.name) }}
      {{ render_field(form.description) }}
      <div class="form-group row">
        <div class="col-sm-10">
          <button type="submit" class="btn btn-primary">Create</button>
        </div>
      </div>
    </form>

    <hr class="separator">
  {%- endif %}

  <table id="attributes_table" class="table table-bordered table-hover table-sm" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>Favorite</th>
        <th>QRCode</th>
        <th>Name</th>
        <th>Description</th>
      </tr>
    </thead>
  </table>
  {%- endblock %}
{%- endblock %}

{% block csentry_scripts %}
  <script src="{{ url_for('static', filename='js/attributes.js') }}"></script>
{% endblock %}

app/templates/inventory/attributes_favorites.html
{% extends "inventory/attributes.html" %}

{% block title %}Attributes favorites{% endblock %}

{% block attributes_main %}
  <table id="attributes_favorites_table" class="table table-bordered table-hover table-sm" cellspacing="0" width="100%">
    <thead>
      <tr>
        <th>QRCode</th>
        <th>Kind</th>
        <th>Name</th>
        <th>Description</th>
      </tr>
    </thead>
  </table>
{%- endblock %}

app/templates/inventory/comment_item.html
{% extends "inventory/view_item.html" %}
{% from "_helpers.html" import item_comment_form %}

  {% block comment_item %}
  {{ item_comment_form(form, item) }}
  {% endblock %}

app/templates/inventory/create_item.html
{% extends "inventory/items.html" %}
{% from "_helpers.html" import render_field, figure %}

{% block title %}Register Item{% endblock %}

{% block items_main %}
  <div class="row">
    <div class="col-sm-11">
      <form id="createItemForm" method="POST">
        {{ form.hidden_tag() }}
        {{ render_field(form.ics_id) }}
        {{ render_field(form.serial_number) }}
        {{ render_field(form.quantity) }}
        {{ render_field(form.manufacturer_id) }}
        {{ render_field(form.model_id) }}
        {{ render_field(form.location_id) }}
        {{ render_field(form.status_id) }}
        {{ render_field(form.parent_id) }}
        {{ render_field(form.host_id) }}
        {{ render_field(form.stack_member) }}
        {{ render_field(form.mac_addresses) }}
        <div class="form-group row">
          <div class="col-sm-10">
            <button type="submit" class="btn btn-primary" id="submit">Submit</button>
            <button type="button" class="btn btn-primary" id="clear">Clear</button>
          </div>
        </div>
      </form>
    </div>
    <div class="col-sm-1">
      {{ figure("actions/submit.png", "Submit") }}
    </div>
  </div>
{%- endblock %}

{% block csentry_scripts %}
  <script src="{{ url_for('static', filename='js/create_item.js') }}"></script>
{% endblock %}

app/templates/inventory/edit_comment.html
{% extends "inventory/view_item.html" %}
{% from "_helpers.html" import item_comment_form, item_comment %}

  {% block comments %}
  {% for comment in item.comments | sort(attribute='created_at') %}
    {% if comment.id == comment_id %}
      {{ item_comment_form(form, item) }}
    {% else %}
      {{ item_comment(comment) }}
    {% endif %}
  {% endfor %}
  {% endblock %}

  {% block comment_item %}
  {% endblock %}

app/templates/inventory/edit_item.html
{% extends "inventory/items.html" %}
{% from "_helpers.html" import render_field %}

{% block title %}Edit {{ form.ics_id.data }} item{% endblock %}

{% block items_nav %}
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('inventory.view_item', ics_id=form.ics_id.data) }}">View item</a>
    </li>
    <li class="nav-item">
      <a class="nav-link active" href="{{ url_for('inventory.edit_item', ics_id=form.ics_id.data) }}">Edit item</a>
    </li>
{% endblock %}


{% block items_main %}
  <form id="editItemForm" method="POST">
    {{ form.hidden_tag() }}
    {% if form.ics_id.data.startswith(config['TEMPORARY_ICS_ID'])  or form.ics_id.errors %}
      {{ render_field(form.ics_id) }}
    {% else %}
      {{ render_field(form.ics_id, readonly=True) }}
    {% endif %}
    {{ render_field(form.serial_number) }}
    {{ render_field(form.quantity) }}
    {{ render_field(form.manufacturer_id) }}
    {{ render_field(form.model_id) }}
    {{ render_field(form.location_id) }}
    {{ render_field(form.status_id) }}
    {{ render_field(form.parent_id) }}
    {{ render_field(form.host_id) }}
    {{ render_field(form.stack_member) }}
    {{ render_field(form.mac_addresses) }}
    <div class="form-group row">
      <div class="col-sm-10">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{%- endblock %}

{% block csentry_scripts %}
  <script src="{{ url_for('static', filename='js/edit_item.js') }}"></script>
{% endblock %}

app/templates/inventory/items.html
{% extends "base-fluid.html" %}
{% from "_helpers.html" import is_active, waiting_for %}

{% block title %}Items{% endblock %}

{% block main %}
  {{ waiting_for("Please wait while your file is being prepared...", "downloadExcelModal") }}
  {% set path = request.path %}
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link {{ is_active(path.endswith("/inventory/items")) }}" href="{{ url_for('inventory.list_items') }}">List items</a>
    </li>
    <li class="nav-item">
      <a class="nav-link {{ is_active(path.startswith("/inventory/items/create")) }}" href="{{ url_for('inventory.create_item') }}">Register new item</a>
    </li>
    {% block items_nav %}{% endblock %}
  </ul>

  <br>

  {% block items_main %}
  <table id="items_table" class="table table-bordered table-hover table-sm" style="width:100%">
    <thead>
      <tr>
        <th>ICS id</th>
        <th>Created</th>
        <th>Updated</th>
        <th>Serial number</th>
        <th>Quantity</th>
        <th>Manufacturer</th>
        <th>Model</th>
        <th>Location</th>
        <th>Status</th>
        <th>Parent</th>
      </tr>
    </thead>
  </table>
  {%- endblock %}
{%- endblock %}

{% block csentry_scripts %}
  <script src="{{ url_for('static', filename='js/items.js') }}"></script>
{% endblock %}

app/templates/inventory/scanner.html
{% extends "base-fluid.html" %}
{% from "_helpers.html" import figure %}

{% block title %}Scanner{% endblock %}

{% block main %}
  <div class="col-md-8">
  <h4 class="text-center">Scan the following codes to change the Xenon 1900 scanner settings</h4>
    <div class="card">
      <h5 class="card-header">Restore default settings</h5>
      <div class="card-body">
        <div class="list-group">
          {{ figure("xenon/activate-custom-defaults.png", "Activate Custom Defaults") }}
          {{ figure("xenon/hand-held-scanning.png", "Hand Held Scanning - Mobile Phone") }}
        </div>
      </div>
    </div>
    </br>
    <div class="card">
      <h5 class="card-header">Lower or disable the sound</h5>
      <div class="card-body">
        <div class="list-group">
          {{ figure("xenon/daytime-mode.png", "Daytime Mode (all sounds to on, but at a low volume)") }}
          {{ figure("xenon/silent-mode-with-flashing-led.png", "Silent Mode With Flashing LED (all sounds are silenced)") }}
        </div>
      </div>
    </div>
    </br>
    <div class="card">
      <h5 class="card-header">Use csentry-scanner application</h5>
      <div class="card-body">
        <p class="card-text">Configure the scanner to emulate a regular RS232-based COM port</p>
        <div class="list-group">
          {{ figure("xenon/rs232-interface.png", "RS232 Interface") }}
          {{ figure("xenon/usb-serial.png", "USB Serial") }}
        </div>
      </div>
    </div>
    </br>
    <div class="card">
      <h5 class="card-header">Scan directly in the web UI</h5>
      <div class="card-body">
        <p class="card-text">Configure the scanner as a keyboard to scan ICS id and serial numbers in the web UI</p>
        <div class="list-group">
          {{ figure("xenon/usb-keyboard-pc.png", "USB Keyboard (PC)") }}
          {{ figure("xenon/usb-keyboard-mac.png", "USB Keyboard (Mac)") }}
        </div>
      </div>
    </div>
  </div>
{%- endblock %}

app/templates/inventory/view_item.html
{% extends "inventory/items.html" %}
{% from "_helpers.html" import link_to_item, link_to_items, format_datetime, link_to_host, item_comment %}

{% block title %}View {{ item.ics_id }} item{% endblock %}

{% block items_nav %}
    <li class="nav-item">
      <a class="nav-link active" href="{{ url_for('inventory.view_item', ics_id=item.ics_id) }}">View item</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ url_for('inventory.edit_item', ics_id=item.ics_id) }}">Edit item</a>
    </li>
{% endblock %}

{% block items_main %}
  <dl class="row">
    <dt class="col-sm-3">ICS id</dt>
    <dd class="col-sm-9">{{ item.ics_id }}</dd>
    <dt class="col-sm-3">Created</dt>
    <dd class="col-sm-9">{{ format_datetime(item.created_at) }}</dd>
    <dt class="col-sm-3">Created by</dt>
    <dd class="col-sm-9">{{ item.user }}</dd>
    <dt class="col-sm-3">Updated</dt>
    <dd class="col-sm-9">{{ format_datetime(item.updated_at) }}</dd>
    <dt class="col-sm-3">Serial number</dt>
    <dd class="col-sm-9">{{ item.serial_number }}</dd>
    <dt class="col-sm-3">Quantity</dt>
    <dd class="col-sm-9">{{ item.quantity }}</dd>
    <dt class="col-sm-3">Manufacturer</dt>
    <dd class="col-sm-9">{{ item.manufacturer }}</dd>
    <dt class="col-sm-3">Model</dt>
    <dd class="col-sm-9">{{ item.model }}</dd>
    {% if item.model.description %}
    <dt class="col-sm-3">Model description</dt>
    <dd class="col-sm-9">{{ item.model.description }}</dd>
    {% endif %}
    <dt class="col-sm-3">Location</dt>
    <dd class="col-sm-9">{{ item.location }}</dd>
    <dt class="col-sm-3">Status</dt>
    <dd class="col-sm-9">{{ item.status }}</dd>
    {% if item.host %}
    <dt class="col-sm-3">Host</dt>
    <dd class="col-sm-9">{{ link_to_host(item.host) }}</dd>
    {% endif %}
    {% if item.stack_member is not none %}
    <dt class="col-sm-3">Stack member</dt>
    <dd class="col-sm-9">{{ item.stack_member }}</dd>
    {% endif %}
    {% for mac in item.macs %}
      {% set macloop = loop %}
      <dt class="col-sm-3">MAC Address{{ loop.index }}</dt>
      <dd class="col-sm-9">{{ mac.address }}</dd>
      {% for interface in mac.interfaces %}
        <dt class="col-sm-3">Interface{{ macloop.index }}-{{ loop.index }}</dt>
        <dd class="col-sm-9">IP: {{ interface.ip }} / name: {{ interface.name }}</dd>
      {% endfor %}
    {% endfor %}
    <dt class="col-sm-3">Parent</dt>
    <dd class="col-sm-9">{{ link_to_item(item.parent) }}</dd>
    <dt class="col-sm-3">Children</dt>
    <dd class="col-sm-9">{{ link_to_items(item.children) }}</dd>
  </dl>

  <h4>Comments</h4>
  {% block comments %}
  {% for comment in item.comments | sort(attribute='created_at') %}
    {{ item_comment(comment) }}
  {% endfor %}
  {% endblock %}

  {% block comment_item %}
  <a class="btn btn-primary" href="{{ url_for('inventory.comment_item', ics_id=item.ics_id) }}#body">Comment</a>
  {% endblock %}

  <hr>

  <h4>History</h4>
  <table id="item_version_table" class="table table-hover table-sm">
    <thead>
      <tr>
        <th>Updated</th>
        <th>Quantity</th>
        <th>Location</th>
        <th>Status</th>
        <th>Parent</th>
      </tr>
    </thead>
    <tbody>
      {% for version in item.history() %}
      <tr>
        <td>{{ version['updated_at'] }}</td>
        <td>{{ version['quantity'] }}</td>
        <td>{{ version['location'] }}</td>
        <td>{{ version['status'] }}</td>
        <td>{{ link_to_item(version['parent']) }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{%- endblock %}