app/inventory/views.py
# -*- coding: utf-8 -*-
"""
app.inventory.views
~~~~~~~~~~~~~~~~~~~

This module implements the inventory blueprint.

:copyright: (c) 2017 European Spallation Source ERIC
:license: BSD 2-Clause, see LICENSE for more details.

"""
import sqlalchemy as sa
from flask import (
    Blueprint,
    render_template,
    jsonify,
    session,
    request,
    redirect,
    url_for,
    flash,
    current_app,
)
from flask_login import login_required, current_user
from .forms import AttributeForm, ItemForm, CommentForm, EditCommentForm
from ..extensions import db
from ..decorators import login_groups_accepted
from .. import utils, models, helpers

bp = Blueprint("inventory", __name__)


@bp.route("/_retrieve_items", methods=["POST"])
@login_required
def retrieve_items():
    return utils.retrieve_data_for_datatables(request.values, models.Item)


@bp.route("/items")
@login_required
def list_items():
    return render_template("inventory/items.html")


@bp.route("/items/_generate_excel_file")
@login_required
def _generate_excel_file():
    task = current_user.launch_task(
        "generate_items_excel_file", func="generate_items_excel_file", job_timeout=180
    )
    db.session.commit()
    return utils.redirect_to_job_status(task.id)


@bp.route("/items/create", methods=("GET", "POST"))
@login_groups_accepted("admin", "inventory")
def create_item():
    # The following keys are stored in the session to easily create
    # several identical items
    keys = ("manufacturer_id", "model_id", "location_id", "status_id", "parent_id")
    settings = {key: session.get(key, "") for key in keys}
    form = ItemForm(request.form, **settings)
    if form.validate_on_submit():
        for key in keys:
            session[key] = getattr(form, key).data
        item = models.Item(
            ics_id=form.ics_id.data,
            serial_number=form.serial_number.data,
            quantity=form.quantity.data,
            manufacturer=helpers.get_model(
                models.Manufacturer, form.manufacturer_id.data
            ),
            model=helpers.get_model(models.Model, form.model_id.data),
            location=helpers.get_model(models.Location, form.location_id.data),
            status=helpers.get_model(models.Status, form.status_id.data),
            parent=helpers.get_model(models.Item, form.parent_id.data),
            host=helpers.get_model(models.Host, form.host_id.data),
            stack_member=form.stack_member.data,
        )
        item.macs = [
            models.Mac(address=address) for address in form.mac_addresses.data.split()
        ]
        current_app.logger.debug(f"Trying to create: {item!r}")
        db.session.add(item)
        try:
            db.session.commit()
        except sa.exc.IntegrityError as e:
            db.session.rollback()
            current_app.logger.warning(f"{e}")
            flash(f"{e}", "error")
        else:
            flash(f"Item {item} created!", "success")
        return redirect(url_for("inventory.create_item"))
    return render_template("inventory/create_item.html", form=form)


@bp.route("/items/view/<ics_id>")
@login_required
def view_item(ics_id):
    item = models.Item.query.filter_by(ics_id=ics_id).first_or_404()
    return render_template("inventory/view_item.html", item=item)


@bp.route("/items/comment/<ics_id>", methods=("GET", "POST"))
@login_groups_accepted("admin", "inventory")
def comment_item(ics_id):
    item = models.Item.query.filter_by(ics_id=ics_id).first_or_404()
    form = CommentForm()
    if form.validate_on_submit():
        comment = models.ItemComment(body=form.body.data)
        item.comments.append(comment)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for("inventory.view_item", ics_id=ics_id))
    return render_template("inventory/comment_item.html", item=item, form=form)


@bp.route("/items/comment/edit/<comment_id>", methods=("GET", "POST"))
@login_groups_accepted("admin", "inventory")
def edit_comment(comment_id):
    comment = models.ItemComment.query.get_or_404(comment_id)
    form = EditCommentForm(request.form, obj=comment)
    if form.validate_on_submit():
        comment.body = form.body.data
        # Mark the item as "dirty" to add it to the session so that it will
        # be re-indexed
        sa.orm.attributes.flag_modified(comment.item, "comments")
        db.session.commit()
        return redirect(url_for("inventory.view_item", ics_id=comment.item.ics_id))
    return render_template(
        "inventory/edit_comment.html",
        item=comment.item,
        comment_id=comment.id,
        form=form,
    )


@bp.route("/items/comment/delete", methods=["POST"])
@login_groups_accepted("admin", "inventory")
def delete_comment():
    comment = models.ItemComment.query.get_or_404(request.form["comment_id"])
    ics_id = comment.item.ics_id
    # Explicitely remove the comment from the item to make sure
    # it will be re-indexed
    comment.item.comments.remove(comment)
    db.session.delete(comment)
    db.session.commit()
    flash(f"Comment {comment.id} has been deleted", "success")
    return redirect(url_for("inventory.view_item", ics_id=ics_id))


@bp.route("/items/edit/<ics_id>", methods=("GET", "POST"))
@login_groups_accepted("admin", "inventory")
def edit_item(ics_id):
    item = models.Item.query.filter_by(ics_id=ics_id).first_or_404()
    mac_addresses = " ".join([str(mac) for mac in item.macs])
    form = ItemForm(request.form, obj=item, mac_addresses=mac_addresses)
    if form.validate_on_submit():
        # Only allow to update temporary ics_id
        if item.ics_id.startswith(current_app.config["TEMPORARY_ICS_ID"]):
            item.ics_id = form.ics_id.data
        item.serial_number = form.serial_number.data
        item.quantity = form.quantity.data
        # When a field is disabled, it's value is not passed to the request
        # We don't use request.form.get('stack_member', None) to let the coerce
        # function of the field properly convert the value
        if "stack_member" in request.form:
            item.stack_member = form.stack_member.data
        else:
            # Field is disabled, force it to None
            item.stack_member = None
        item.manufacturer = helpers.get_model(
            models.Manufacturer, form.manufacturer_id.data
        )
        item.model = helpers.get_model(models.Model, form.model_id.data)
        item.location = helpers.get_model(models.Location, form.location_id.data)
        item.status = helpers.get_model(models.Status, form.status_id.data)
        item.parent = helpers.get_model(models.Item, form.parent_id.data)
        item.host = helpers.get_model(models.Host, form.host_id.data)
        new_addresses = form.mac_addresses.data.split()
        # Delete the MAC addresses that have been removed
        for (index, mac) in enumerate(item.macs):
            if mac.address not in new_addresses:
                item.macs.pop(index)
                db.session.delete(mac)
        # Add new MAC addresseses
        for address in new_addresses:
            if address not in mac_addresses:
                mac = models.Mac(address=address)
                item.macs.append(mac)
        current_app.logger.debug(f"Trying to update: {item!r}")
        try:
            db.session.commit()
        except sa.exc.IntegrityError as e:
            db.session.rollback()
            current_app.logger.warning(f"{e}")
            flash(f"{e}", "error")
        else:
            flash(f"Item {item} updated!", "success")
        return redirect(url_for("inventory.view_item", ics_id=item.ics_id))
    return render_template("inventory/edit_item.html", form=form)


@bp.route("/attributes/favorites")
@login_required
def attributes_favorites():
    return render_template("inventory/attributes_favorites.html")


@bp.route("/_retrieve_attributes_favorites")
@login_required
def retrieve_attributes_favorites():
    data = [
        (
            favorite.base64_image(),
            type(favorite).__name__,
            favorite.name,
            favorite.description,
        )
        for favorite in current_user.favorite_attributes()
    ]
    return jsonify(data=data)


@bp.route("/attributes/<kind>", methods=("GET", "POST"))
@login_groups_accepted("admin", "inventory")
def attributes(kind):
    form = AttributeForm()
    if form.validate_on_submit():
        model = getattr(models, kind)
        new_model = model(
            name=form.name.data, description=form.description.data or None
        )
        db.session.add(new_model)
        try:
            db.session.commit()
        except sa.exc.IntegrityError:
            db.session.rollback()
            flash(f"{form.name.data} already exists! {kind} not created.", "error")
        else:
            flash(f"{kind} {new_model} created!", "success")
        return redirect(url_for("inventory.attributes", kind=kind))
    return render_template("inventory/attributes.html", kind=kind, form=form)


@bp.route("/_retrieve_attributes/<kind>")
@login_required
def retrieve_attributes(kind):
    try:
        model = getattr(models, kind)
    except AttributeError:
        raise utils.CSEntryError(f"Unknown model '{kind}'", status_code=422)
    items = db.session.query(model).order_by(model.name)
    data = [
        (
            {"id": item.id, "favorite": item.is_user_favorite()},
            item.base64_image(),
            item.name,
            item.description,
        )
        for item in items
    ]
    return jsonify(data=data)


@bp.route("/_update_favorites/<kind>", methods=["POST"])
@login_required
def update_favorites(kind):
    """Update the current user favorite attributes

    Add or remove the attribute from the favorites when the
    checkbox is checked/unchecked in the attributes table
    """
    try:
        model = getattr(models, kind)
    except AttributeError:
        raise utils.CSEntryError(f"Unknown model '{kind}'", status_code=422)
    data = request.get_json()

app/main/views.py
# -*- coding: utf-8 -*-
"""
app.main.views
~~~~~~~~~~~~~~

This module implements the main blueprint.

:copyright: (c) 2017 European Spallation Source ERIC
:license: BSD 2-Clause, see LICENSE for more details.

"""
import os
import redis
import rq
import rq_dashboard
from flask import Blueprint, render_template, jsonify, g, current_app, abort, request
from flask_login import login_required, current_user
from rq import push_connection, pop_connection
from sentry_sdk import last_event_id
from .. import utils

bp = Blueprint("main", __name__)


# Allow only admin to access the RQ Dashboard
@rq_dashboard.blueprint.before_request
@login_required
def before_request():
    if not current_user.is_admin:
        abort(403)


# Declare custom error handlers for all views
@bp.app_errorhandler(403)
def forbidden_error(error):
    return render_template("403.html"), 403


@bp.app_errorhandler(404)
def not_found_error(error):
    if (
        request.path.startswith("/api")
        or request.accept_mimetypes.best == "application/json"
    ):
        # API request - return json
        return jsonify({"message": "Resource not found"}), 404
    else:
        return render_template("404.html"), 404


@bp.app_errorhandler(500)
def internal_error(error):
    return (render_template("500.html", sentry_event_id=last_event_id()), 500)


@bp.app_errorhandler(utils.CSEntryError)
def handle_csentry_error(error):
    response = jsonify(error.to_dict())
    response.status_code = error.status_code
    return response


@bp.app_url_defaults
def modified_static_file(endpoint, values):
    """Add a last modified query parameter to static resource

    Force the browser to invalidate the cache and reload resources
    when files have changed

    Inspired from http://flask.pocoo.org/snippets/40/ and
    https://gist.github.com/Ostrovski/f16779933ceee3a9d181
    """
    if endpoint == "static":
        filename = values.get("filename")
        if filename:
            # The same static folder is used for all blueprints
            file_path = os.path.join(current_app.static_folder, filename)
            values["m"] = int(os.stat(file_path).st_mtime)


def get_redis_connection():
    redis_connection = getattr(g, "_redis_connection", None)
    if redis_connection is None:
        redis_url = current_app.config["RQ_REDIS_URL"]
        redis_connection = g._redis_connection = redis.from_url(redis_url)
    return redis_connection


@bp.before_app_request
def push_rq_connection():
    push_connection(get_redis_connection())


@bp.teardown_app_request
def pop_rq_connection(exception=None):
    pop_connection()


@bp.route("/")
@login_required
def index():
    """Return the application index"""
    return render_template("index.html")


@bp.route("/status/<job_id>")
@login_required
def job_status(job_id):
    """Return the status of the job

    :param int job_id: The id of the job to pull
    :return: json with the status of the job
    """
    job = rq.job.Job.fetch(job_id)
    if job is None:
        response = {"status": "unknown"}
    else:
        response = {
            "status": job.get_status(),
            "result": job.result,
            "func_name": job.func_name.split(".")[-1],
            "progress": job.meta.get("progress"),
        }
        if job.is_failed:
            response["message"] = job.meta.get("error", "Job failed")
    return jsonify(response)

app/task/views.py
# -*- coding: utf-8 -*-
"""
app.task.views
~~~~~~~~~~~~~~

This module implements the task blueprint.

:copyright: (c) 2018 European Spallation Source ERIC
:license: BSD 2-Clause, see LICENSE for more details.

"""
from flask import Blueprint, render_template, jsonify, request
from flask_login import login_required, current_user
from .. import models

bp = Blueprint("task", __name__)


@bp.route("/tasks")
@login_required
def list_tasks():
    return render_template("task/tasks.html")


@bp.route("/tasks/view/<id_>")
@login_required
def view_task(id_):
    task = models.Task.query.get_or_404(id_)
    return render_template("task/view_task.html", task=task)


@bp.route("/_retrieve_tasks")
@login_required
def retrieve_tasks():
    all = request.args.get("all", "false") == "true"
    data = [task.to_dict() for task in current_user.get_tasks(all=all)]
    return jsonify(data=data)

app/user/views.py
# -*- coding: utf-8 -*-
"""
app.user.views
~~~~~~~~~~~~~~

This module implements the user blueprint.

:copyright: (c) 2017 European Spallation Source ERIC
:license: BSD 2-Clause, see LICENSE for more details.

"""
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    flash,
    current_app,
    session,
)
from flask_login import login_user, logout_user, login_required, current_user
from flask_ldap3_login.forms import LDAPLoginForm
from .forms import TokenForm
from .. import tokens, utils

bp = Blueprint("user", __name__)


@bp.route("/login", methods=["GET", "POST"])
def login():
    """Login page"""
    form = LDAPLoginForm(request.form)
    if form.validate_on_submit():
        login_user(form.user, remember=form.remember_me.data)
        return redirect(request.args.get("next") or url_for("main.index"))
    return render_template("user/login.html", form=form)


@bp.route("/logout")
@login_required
def logout():
    """Logout endpoint"""
    logout_user()
    return redirect(url_for("user.login"))


@bp.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    """User profile"""
    # Try to get the generated token from the session
    token = session.pop("generated_token", None)
    form = TokenForm(request.form)
    if form.validate_on_submit():
        token = tokens.generate_access_token(
            identity=current_user.id,
            expires_delta=False,
            description=form.description.data,
        )
        # Save token to the session to retrieve it after the redirect
        session["generated_token"] = token
        flash(
            "Make sure to copy your new personal access token now. You won’t be able to see it again!",
            "success",
        )
        return redirect(url_for("user.profile"))
    return render_template(
        "user/profile.html", form=form, user=current_user, generated_token=token
    )


@bp.route("/tokens/revoke", methods=["POST"])
@login_required
def revoke_token():
    """Endpoint to revoke a token"""
    token_id = request.form["token_id"]
    jti = request.form["jti"]
    try:
        tokens.revoke_token(token_id, current_user.id)
    except utils.CSEntryError as e:
        current_app.logger.warning(e)
        flash(
            f"Could not revoke the token {jti}. Please contact an administrator.",
            "error",
        )
    else:
        flash(f"Token {jti} has been revoked", "success")
    return redirect(url_for("user.profile"))

app/templates/base-fluid.html
{% extends "base.html" %}
{% from "_helpers.html" import is_active, flashed_messages %}

{# overwrite the base content block to use container-fluid instead of container #}
{% block content %}
<div class="container-fluid">
  <div class="row">

    <div class="col-12 col-md-2 col-xl-2">
      {% set path = request.path %}
      <div class="list-group">
        {% if path.startswith("/inventory") %}
        <a class="list-group-item list-group-item-action {{ is_active(path.startswith("/inventory/items")) }}"
          href="{{ url_for('inventory.list_items') }}">Items</a>
        <a class="list-group-item list-group-item-action {{ is_active(path.startswith("/inventory/attributes")) }}"
          href="{{ url_for('inventory.attributes', kind='Manufacturer') }}">Attributes</a>
        <a class="list-group-item list-group-item-action {{ is_active(path.startswith("/inventory/scanner")) }}"
          href="{{ url_for('inventory.scanner') }}">Scanner setup</a>
        {% elif path.startswith("/network") %}
        <a class="list-group-item list-group-item-action {{ is_active(path.startswith(("/network/hosts", "/network/interfaces"))) }}"
          href="{{ url_for('network.list_hosts') }}">Hosts</a>
        <a class="list-group-item list-group-item-action {{ is_active(path.startswith("/network/networks")) }}"
          href="{{ url_for('network.list_networks') }}">Networks</a>
        <a class="list-group-item list-group-item-action {{ is_active(path.startswith("/network/scopes")) }}"
          href="{{ url_for('network.list_scopes') }}">Network Scopes</a>
        <a class="list-group-item list-group-item-action {{ is_active(path.startswith("/network/domains")) }}"
          href="{{ url_for('network.list_domains') }}">Domains</a>
        <a class="list-group-item list-group-item-action {{ is_active(path.startswith("/network/groups")) }}"
          href="{{ url_for('network.list_ansible_groups') }}">Ansible groups</a>
        {% elif path.startswith("/task") %}
        <a class="list-group-item list-group-item-action {{ is_active(path.startswith("/task/tasks")) }}"
          href="{{ url_for('task.list_tasks') }}">Tasks</a>
        {% endif %}
      </div>
    </div>

    <div class="col-12 col-md-10 col-xl-10" id="mainContent">
      {{flashed_messages(messages, container=False, dismissible=True)}}
      {% block main %}{% endblock %}
    </div>

  </div>
</div>
{% endblock %}

app/templates/base.html
{%- extends "bootstrap.html" %}
{% from "_helpers.html" import is_active, flashed_messages %}

{% block styles %}
  {{super()}}
  <link href="{{ url_for('static', filename='css/open-iconic-bootstrap.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/datatables.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/selectize.bootstrap4.min.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/codemirror.css') }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/csentry.css') }}" rel="stylesheet">
{% endblock %}

{% block title %}CSEntry{% endblock %}

{% block navbar %}
  <!-- Fixed navbar -->
  <div class="navbar fixed-top navbar-expand-lg" role="navigation">
    <a class="navbar-brand" href="{{ url_for('main.index') }}">
       {% if config['CSENTRY_ENVIRONMENT'] == "staging" %}
       <img src="{{ url_for('static', filename='img/CS_entry_TEST_v03.gif') }}" alt="CSEntry TEST">
       {% else %}
       <img src="{{ url_for('static', filename='img/CS_entry_v02_verylightblue.svg') }}" alt="CSEntry">
       {% endif %}
   </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse"
              data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="navbar-nav mr-auto">
          {% set path = request.path %}
          <a class="nav-item nav-link {{ is_active(path.startswith("/inventory")) }}" href="{{ url_for('inventory.list_items') }}">Inventory</a>
          <a class="nav-item nav-link {{ is_active(path.startswith("/network")) }}" href="{{ url_for('network.list_hosts') }}">Network</a>
          <a class="nav-item nav-link {{ is_active(path.startswith("/task")) }}" href="{{ url_for('task.list_tasks') }}">Task</a>
          {% if current_user.is_authenticated and current_user.is_admin %}
            <a class="nav-item nav-link" href="{{ url_for('admin.index') }}">Admin</a>
            <a class="nav-item nav-link" href="{{ url_for('rq_dashboard.overview') }}">RQ Dashboard</a>
          {% endif %}
          <a class="nav-item nav-link" href="{{ config['DOCUMENTATION_URL'] }}" target="_blank">Help</a>
        </div>
        <div class="navbar-nav navbar-right">
          {% block navbar_right %}{% endblock %}
          <span class="navbar-text">Version {{ __version__ }}</span>
          {% if current_user.is_authenticated %}
          <div class="dropdown {{ is_active(path == "/user/profile") }}">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ current_user.display_name }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{{ url_for('user.profile') }}">Profile</a>
              <a class="dropdown-item" href="{{ url_for('user.logout') }}">Logout</a>
            </div>
          </div>
          {% endif %}
        </div>
      </div>
  </div>
{% endblock %}

{% block content %}
  <div class="container" id="mainContent">
    {{flashed_messages(messages, container=False, dismissible=True)}}
    {% block main %}{% endblock %}
  </div>
{% endblock %}

{% block scripts %}
  {{super()}}
  <script src="{{ url_for('static', filename='js/datatables.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/selectize.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/clipboard.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/showdown.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/codemirror.js') }}"></script>
  <script src="{{ url_for('static', filename='js/yaml.js') }}"></script>
  <script src="{{ url_for('static', filename='js/cm-resize.js') }}"></script>
  <script type=text/javascript>
    $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
  </script>
  <script src="{{ url_for('static', filename='js/history.js') }}"></script>
  <script src="{{ url_for('static', filename='js/csentry.js') }}"></script>
  {% block csentry_scripts %}{% endblock %}
{% endblock %}

app/templates/bootstrap.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="CSEntry">
    <meta name="author" content="Benjamin Bertrand">

    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='favicon/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicon/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon/favicon-16x16.png') }}">
    <link rel="manifest" href="{{ url_for('static', filename='favicon/site.webmanifest') }}">
    <link rel="mask-icon" href="{{ url_for('static', filename='favicon/safari-pinned-tab.svg') }}" color="#5bbad5">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon/favicon.ico') }}">
    <meta name="msapplication-TileColor" content="#2b5797">
    <meta name="msapplication-config" content="{{ url_for('static', filename='favicon/browserconfig.xml') }}">
    <meta name="theme-color" content="#ffffff">

    <title>{% block title %}{% endblock %}</title>

    {%- block styles %}
      <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    {%- endblock styles %}
  </head>

  <body>
   {% block body -%}
   {% block navbar %}
   {%- endblock navbar %}
   {% block content -%}
   {%- endblock content %}

   {% block scripts %}
    <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
   {%- endblock scripts %}
   {%- endblock body %}
  </body>
</html>

app/templates/index.html
{%- extends "base.html" %}

{% block main %}
  <div class="jumbotron">
    <h1 class="display-4">
      <img src="{{ url_for('static', filename='img/CS_entry_v02_verylightblue.svg') }}" alt="CSEntry" class="img-fluid">
    </h1>
    <p class="lead">Control System Entry allows you to easily register items and network devices.</lead>
  </div>
{%- endblock %}